### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by wenbinobject** [reactjser/vue3-virtual-scroll-list#12]
![image](https://user-images.githubusercontent.com/21998076/226647368-b35650f9-4f2a-4994-8d89-5a2b18920299.png)

**Comment by wenbinobject** [comment]
ERROR  [vite-plugin-eslint] Failed to load config "@vue/typescript/recommended" to extend from.
Referenced from: /Users/user/Desktop/project/web-swap/.eslintrc.js
file: /Users/user/Desktop/project/web-swap/node_modules/vue/dist/vue.runtime.esm-bundler.js


 ERROR  Failed to load config "@vue/typescript/recommended" to extend from.
Referenced from: /Users/user/Desktop/project/web-swap/.eslintrc.js

  Referenced from: .eslintrc.js
  at configInvalidError (node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2624:9)
  at ConfigArrayFactory._loadExtendedShareableConfig (node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3242:23)
  at ConfigArrayFactory._loadExtends (node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3119:25)
  at ConfigArrayFactory._normalizeObjectConfigDataBody (node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3058:25)
  at _normalizeObjectConfigDataBody.next (<anonymous>)
  at ConfigArrayFactory._normalizeObjectConfigData (node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3003:20)
  at _normalizeObjectConfigData.next (<anonymous>)
  at ConfigArrayFactory.loadInDirectory (node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2849:28)
  at CascadingConfigArrayFactory._loadConfigInAncestors (node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3833:46)
  at CascadingConfigArrayFactory._loadConfigInAncestors (node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3852:20)

Build Failed
